apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
    app: nginx
  ipFamilies:
  - IPv4
  - IPv6
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  ipFamilyPolicy: PreferDualStack
  type: LoadBalancer
