apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
kind: KamajiControlPlane
metadata:
  name: {{ .Values.cluster.name }}
  annotations:
    metallb.universe.tf/loadBalancerIPs: {{ .Values.serviceAddress }}
spec:
  dataStoreName: default
  kubelet:
    cgroupfs: systemd
    preferredAddressTypes:
      - ExternalIP
      - InternalIP
      - Hostname
  addons:
    coreDNS: { }
    kubeProxy: { }
  network:
    serviceType: LoadBalancer
    serviceAddress: {{ .Values.serviceAddress }}
  deployment:
  replicas: 2
  version: 1.28.5
