apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: md-{{ .Values.cluster.name }}
  namespace: default
  labels:
    cluster.x-k8s.io/cluster-name: {{ .Values.cluster.name }}
    nodepool: nodepool-0
spec:
  clusterName: {{ .Values.cluster.name }}
  replicas: 1
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: {{ .Values.cluster.name }}
      nodepool: nodepool-0
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: {{ .Values.cluster.name }}
        nodepool: nodepool-0
    spec:
      nodeDrainTimeout: "0s"
      clusterName: {{ .Values.cluster.name }}
      version: v1.28.1
      bootstrap:
        configRef:
          name: {{ .Values.cluster.name }}-workers
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
      infrastructureRef:
        name: {{ .Values.cluster.name }}-workers-v1-28-4
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: Metal3MachineTemplate
