apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: {{ .Values.cluster.name }}
  namespace: default
spec:
  clusterNetwork:
    services:
      cidrBlocks:
      - 10.96.0.0/12
    pods:
      cidrBlocks:
      - 192.168.0.0/18
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: Metal3Cluster
    name: {{ .Values.cluster.name }}
    namespace: default
  controlPlaneRef:
    kind: KamajiControlPlane
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    name: {{ .Values.cluster.name }}
    namespace: default
