apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3Cluster
metadata:
  name: {{ .Values.cluster.name }}
  namespace: default
spec:
  controlPlaneEndpoint:
    host: {{ .Values.serviceAddress }}
    port: 6443
  noCloudProvider: true
